### ISSUE TITLE
Proposal: kool preset [preset] --wizard | Tailor the presets

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/kool#11]
Would be great to have the `kool init` flexible enough for people to use different database services, or cache services, or even remove those if they don't wanna use them.

---

Nice tool for CLI input: https://github.com/AlecAivazis/survey

---

### TODO

- [x] Given the chosen preset we need to know the options that are adjustable interactively. Figure out a way to have this.

- [x] Provided the chosen options, we then need to build up the final configuration based on the preset templates, that will have to be split up in order to ease up this process.

**Comment by fabriciojs** [comment]
Use cases:

```
$ kool init
     > What preset you wanna use?
         > Laravel
            Adonis
            NextJS
            NuxtJS
      > What database service you wanna use?
          > Mysql
              MariaDB
              Postgress
              None
      > What cache service you wanna use?
          > Redis
              Memcached
              None
```

**Comment by danielsuguimoto** [comment]
another package to consider using: https://github.com/manifoldco/promptui

**Comment by fabriciojs** [comment]
@danielsuguimoto nice!

We also should think about what options we are willing to give initially...

It is important we have them tested and working, so, fewer stable options is certainly better than a lot of options with hiccups in the way.

Starting to think for Laravel for example:

**Databases**
- Mysql (5.7, 8.0)
- Postgress (version?)
- MariaDB (version?)
- None - we do not put in a `database` service

**Application**
- PHP (7.4, 7.3, 7.2)

**Comment by fabriciojs** [comment]
@danielsuguimoto right now I see we have "scrolling" in the list.

![image](https://user-images.githubusercontent.com/1116377/96151587-f4a7cc00-0ee1-11eb-8456-85c241d79a96.png)


The filtering feature is really nice. I guess we should just think about an UX where we avoid more than 5-6 options at a time, so no scrolling happens. (i.e asking something before, like, `project language: PHP, JS, Go`.

**Comment by danielsuguimoto** [comment]
@fabriciojs do we change presets folders structure? Or do you have any idea in mind to relate presets to languages, for example?

**Comment by fabriciojs** [comment]
@danielsuguimoto now that we have https://github.com/kool-dev/kool/pull/172 merged, this would be a breaking change... I think we make it to `2.0.0` or we could add back a command `init` that prompts a deprecated message and proxies to kool preset. What do you think?

**Comment by danielsuguimoto** [comment]
My idea is to use the same idea of presets folder, where we put the yml files within docker-compose blocks and parse them, the same way we do with presets files. For example: `templates/databsase/mysql8.yml`, where we put the image, environments, and volumes parts of the docker-compose for the database service.

**Comment by danielsuguimoto** [comment]
@dbpolito @fabriciojs just to illustrate the idea https://github.com/kool-dev/kool/compare/master...danielsuguimoto:custom-compose?expand=1

**Comment by danielsuguimoto** [comment]
talking to @dbpolito, we found out one more step to this ticket: customize also `kool.yml`

**Comment by fabriciojs** [comment]
@danielsuguimoto that is right, I guess you would want to confirm whether the user wants to use `npm` or `yarn`, `composer` v1 or v2, stuff like that?

Let's create a new ticket to handle that so we can close this one, just linking it!

**Comment by danielsuguimoto** [comment]
@fabriciojs yep! After merging #220, we can start it...

**Comment by fabriciojs** [comment]
@danielsuguimoto for customising `kool.yml` I would like to simply a bit the current template/questions structure. We shall discuss on a new ticket.
