### ISSUE TITLE
Update Kool

### ISSUE THREAD

**Issue by diegohcosta** [kool-dev/kool#112]
To update the kool in my repository, it was necessary to run: sudo kool self-update, as it returned the following message on the output: Kool self-update failed: open /usr/local/bin/.kool.new: permission denied

**Comment by fabriciojs** [comment]
Thanks for creating this issue!

@diegohcosta this is expected, as you are running on Linux I assume, you probably installed with `sudo` like described in the documentation, therefore for self-updating you will also need `sudo` to replace the binary.

We already mentioned about improving some control on `self-update` where we check if elevation is needed but didn't took place so we show a clearer message (see discussion on #88 ).

Therefore I will close this a non-issue, and when we have the improved error message it will refer to #88 original discussion.

But if you think there is other issue than what I described above please feel free to reopen this.
