### ISSUE TITLE
Proposal: Notification for when a new patch/release version of kool is available

### ISSUE THREAD

**Issue by nkabz** [kool-dev/kool#132]
Got the idea from the NPM notification system:

![image](https://user-images.githubusercontent.com/17432496/94836081-eb4e3800-03e8-11eb-86ae-46a4eaada2e9.png)

Maybe we could make a get request when a user uses `kool start` and notify when the containers are up if theres a new version available?

**Comment by danielsuguimoto** [comment]
@fabriciojs @dbpolito @nkabz how about notifying the user also on `kool stop` and `kool status`?

**Comment by dbpolito** [comment]
That sounds good... i think we need to cache to check / show this message once a day. Maybe have this configurable too somehow.

**Comment by fabriciojs** [comment]
@nkabz -

Caching is important, we can use some touch temporary file for that. I don't see a need for extra configuration.

The biggest concern though is not impacting the overall user experience. So any processing on this should take place concurrently to whatever main processing is meant by the command (start/stop/status), and at the end of the main command, check if we got a result; if not (maybe GithubAPI / user connection is really slow), we simply give up and pretend nothing even happened, but we do not need to wait for this as it is an adjacent feature.

**Comment by fabriciojs** [comment]
This has been implemented and is already shipped into recent Kool releases!
