### ISSUE TITLE
Automatically tell TTY environment so we don't need flags/env vars

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/kool#137]
**Describe the feature**

Would be great if we could automatically tell whether we are running in a terminal of not, so toggle the TTY flags on Docker and Docker Compose commands.

**Backward compatibility concerns**

No BC concerns.

**Use cases**

Running commands in a Cron or CI environment, we would no longer explicitly disable TTY.

**Resources**

- https://rosettacode.org/wiki/Check_output_device_is_a_terminal#Go

**Comment by fabriciojs** [comment]
How Docker checks for it: https://github.com/docker/cli/blob/f8696535e9e516a5a404661697fef6f1228ada64/cli/streams/in.go#L42

**Comment by fabriciojs** [comment]
Using `github.com/moby/term` - https://github.com/moby/term/blob/master/term.go#L41-L55

**Comment by fabriciojs** [comment]
@danielsuguimoto @dbpolito - thinking about User Experience, and the goal of `kool` to simplify/removing learning curve of Docker/DockerCompose, I believe that this feature should be a priority as it certainly would remove countless errors in future usage, which would depend on knowledge over specifics TTY and Docker.

What do you guys think about prioritising this?

**Comment by danielsuguimoto** [comment]
Sounds great! It's a simple feature, but would be a huge improvement.

**Comment by dbpolito** [comment]
I agree, this is going to improve UX a lot.
