### ISSUE TITLE
NextJS is duplicated on README

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#145]
On README Framework presets section, NextJS is duplicated. One of them should be NestJS.

**Comment by tullur** [comment]
Hi, I'll fix it.

**Comment by tullur** [comment]
Hm, PR https://github.com/kool-dev/kool/pull/146, this is already done.

**Comment by fabriciojs** [comment]
Yeah @tullur, this one is already handled, closing it now.

Thanks for interest in helping though, feel free to give it a crack on other issues as well!
