### ISSUE TITLE
Remove TTY flags from presets files

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#153]
**Describe the feature**

We have deprecated the `--disable-tty` flag and the `KOOL_TTY_DISABLE` environment variable. but they weren't removed from the presets files. We should remove them before dropping them from `kool`

**Backward compatibility concerns**

Can be a BC if `no-tty` alike scripts were being used by the final users for some reason.

**Comment by fabriciojs** [comment]
@danielsuguimoto I don't see it as BC because people using `no-tty` would still have that preset in their projects, and the flag will keep working... if they want to they can update the preset and be safe for 2.0 when the flag is removed. We should already remove them from the preset now I guess.
