### ISSUE TITLE
Proposal: kool create

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/kool#17]
Create a new project for the presets we already handle.

For example, `kool create laravel my-laravel-app` would create a new project laravel from scratch using composer project-create in a `my-laravel-app` folder in the current working dir.

**Comment by danielsuguimoto** [comment]
I've added a metafile with some info about the preset on this pull request https://github.com/kool-dev/kool/pull/172
With this metafile, we will be able to set a create-project command as well.

**Comment by fabriciojs** [comment]
Awesome! @tiagoguirado or @nkabz  do you wanna tackle this one? 😃 👀

**Comment by leandroncbrito** [comment]
I'll tackle this one

**Comment by dbpolito** [comment]
Thanks @leandroncbrito for your contribution, looking great.
