### ISSUE TITLE
Upgrade cobra to make kool run autocomplete

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#171]
`kool run` scripts autocomplete for zsh is possible today only loading the entire list of scripts before. Lazy autocomplete is possible only version `1.1.0` or greater of cobra, and we use `1.0.0` today. 

https://github.com/spf13/cobra/pull/1070

This is the PR that enables zsh lazy completions, available only on `1.1.0`

**Comment by fabriciojs** [comment]
Good catch 👍🏻  I say this is a nice UX feat!
