### ISSUE TITLE
Remove TTY related flags

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#174]
**Describe the feature**

When we got ready for `2.0.0`, remove TTY related flags.

**Backward compatibility concerns**

Would this be BC? Users should remove these flags from every script they have.

**Use cases**

Kool auto-detect if the environment is a terminal, so these flags are not necessary.

**Comment by fabriciojs** [comment]
@danielsuguimoto we can start already working on `2.0` in a new branch, so we have stuff like this being prepared while we are not ready to publish it.

**Comment by fabriciojs** [comment]
Done and merged onto 2.0.

**Comment by fabriciojs** [comment]
@danielsuguimoto I added the label 2.0, we should add it to tasks/PRs so we can then properly create a changelog when we do 2.0
