### ISSUE TITLE
Error when using * in a kool.yml command

### ISSUE THREAD

**Issue by leandroncbrito** [kool-dev/kool#183]
**Describe the bug**

In kool.yml the asterisk is being taken literally.

**Kool version and environment**

version: 1.6.0
OS: macOS Catalina 10.15.7
info:
KOOL_NAME=kool
KOOL_GLOBAL_NETWORK=kool_global
KOOL_ASUSER=502

**To Reproduce**

In kool.yml

```
scripts:
  create:
    - cp -rf /app/* ./app2
```

**Error:**
cp: app/*: No such file or directory

**Expected behavior**

All files of folder **/app** copied to **./app2** folder

**Additional context**

workaround to solve the problem
`bash -c 'cp -rf /app/* ./app2'`

**Comment by fabriciojs** [comment]
So this seams like a misconception (at least from my part) when running commands with exec.Cmd versus actual shell (sh, bash). Work the shell does for us behind the scenes that we don't even know.

> When you type the command at the shell, the shell takes ./source_dir/* and replaces it with a list of all of the files that match, one per argument. The mv command sees a list of filenames, not a wildcard.
> 
> What you need to do is either do the same thing yourself (using filepath.Glob which returns a []string of matching files), or to invoke the shell so that it can do the work (using exec.Command("/bin/sh", "-c", "mv ./source_dir/* ./dest_dir")).

https://stackoverflow.com/questions/31467153/golang-failed-exec-command-that-works-in-terminal

---

Given that we need to assess our options:

1. Do we want to support wildcards?
2. Can we simply proxy it to a shell (current shell/default shell)?
3. Do we wanna parse the path globs ourselves? Expand the wildcards? Maybe we can use some Golang/shell library to handle this? (i.e [elvish](https://github.com/elves/elvish) - specifically [here](https://github.com/elves/elvish/blob/1dbccad5710c9c078f05f9e2011e1f29b674ef48/pkg/glob/parse.go) and in the other files at the same package).

@danielsuguimoto @dbpolito - thoughts?

**Comment by danielsuguimoto** [comment]
another workaround: use https://github.com/kool-dev/docker-bash

**Comment by fabriciojs** [comment]
> another workaround: use https://github.com/kool-dev/docker-bash

I don't see this as an option... spanning a new container to run `bash` certainly would solve the wildcard expansion, but what about the actual command intended? if that is a usual Unix command like cp/rm/mv/etc, OK, but we can have ANY think in the script, so we cannot run it from within a new container environment.

**Comment by dbpolito** [comment]
Windows do not have bash =), no idea about wildcard too on their powershell stuff...

I would say `docker-bash` looks good to me too, we can just have a script on every preset, like: `bash: kool docker kooldev/bash` and on any project we can just do `kool run bash` for these stuff...

But maybe defaulting simple commands to `$SHELL -c "$cmd"` might be a good idea...

**Comment by fabriciojs** [comment]
Closing as we have an entry on the documentation stating this about this - we don't support it out of the box, but people are advised to use `bash -c ""` or similar in case they need it.

https://github.com/kool-dev/kool/blob/master/docs/1-Getting-Started/4-How-it-works.md#what-kind-of-commands-can-be-encasulated-on-koolyml
