### ISSUE TITLE
"Creating network" issue when running kool start

### ISSUE THREAD

**Issue by hethini-ribeiro** [kool-dev/kool#188]
This error may indicate that we have a **lot of docker networks created**. 

![image](https://user-images.githubusercontent.com/72409116/97475808-76f5ae80-192c-11eb-8e3a-57e3ad3902e8.png)

We can check this by running **docker network ls**

![image](https://user-images.githubusercontent.com/72409116/97480171-d4402e80-1931-11eb-92a4-f28a23458262.png)

In order to solve this, we can run **docker network prune**

![image](https://user-images.githubusercontent.com/72409116/97480230-e621d180-1931-11eb-8e00-022dd085b82d.png)

And as result, we can check again:

![image](https://user-images.githubusercontent.com/72409116/97480435-26814f80-1932-11eb-874a-76d9cae4913d.png)

**Comment by fabriciojs** [comment]
It appears that docker has a limit on how many networks are created. This should be an edge case, reaching such limit.

Just like mentioned in #189 maybe we can parse the error to check if we know how to solve it, and then we can print some helping message/directions.

**Comment by fabriciojs** [comment]
Also related to network creation - the create network command output is going to STDOUT, where it should be omitted.

**Comment by fabriciojs** [comment]
This will be handled at https://github.com/kool-dev/kool/issues/279 along with other error output situations that require improvements. Closing this now, and progress should be discussed/followed in the centralized issue.
