### ISSUE TITLE
Error when trying to connect in address already in use

### ISSUE THREAD

**Issue by hethini-ribeiro** [kool-dev/kool#189]
This error can be caused when we are **trying to connect to an occupied port.**

![Screenshot from 2020-10-28 14-49-33](https://user-images.githubusercontent.com/72409116/97481296-5b41d680-1933-11eb-8009-60b01302bc7b.png)

One way to resolve this is to stop running softwares that may be using these ports, such as Apache. 
But we can also solve this issue using another port that is probably available.
We can force Kool to do this by **adding these constants to the end of the .env file in your project:**

_**KOOL_APP_PORT=8080
KOOL_DATABASE_PORT=13306**_

Like this:

![image](https://user-images.githubusercontent.com/72409116/97484408-7a426780-1937-11eb-87fe-0025875ff226.png)

**Comment by fabriciojs** [comment]
Thanks for the report @hethini-ribeiro !

@danielsuguimoto @dbpolito - this kind of error I suppose is very common, and requires a bit of understanding of network ports and containers network port configuration as well. I guess there is good room here for:

- Improving documentation on environment variables available for tweaking i.e the ports, and how/when to use them;
- Improving documentation on usual issues;
- Maybe we can improve our error handling, detect the kind of known error that happened, to provide the user with a better message/direction on how to solve it.

**Comment by fabriciojs** [comment]
This will be handled at https://github.com/kool-dev/kool/issues/279 along with other error output situations that require improvements. Closing this now, and progress should be discussed/followed in the centralized issue.
