### ISSUE TITLE
Proposal: kool self-update

### ISSUE THREAD

**Issue by dbpolito** [kool-dev/kool#2]
Under Linux (and any system that allows for it) would be great to have a simple and quick tool for updating kool. Self update is a great way of doing it.

`kool self-update` - checks the latest release somewhere like i.e `https://kool.dev/releases/latest/version`; if necessary to upgrade, downloads and replace the appropriate binary.

**Comment by fabriciojs** [comment]
https://github.com/sanbornm/go-selfupdate

https://github.com/inconshreveable/go-update

**Comment by fabriciojs** [comment]
Since we plan on having an increased frequency of releases, having this feature should be of a good deal of value.

**Comment by fabriciojs** [comment]
Will prioritise this one next for MacOS/Linux.

**Comment by fabriciojs** [comment]
Implemented and will be tested after next release.

**Comment by fabriciojs** [comment]
It is working now starting at 1.0.17!

![image](https://user-images.githubusercontent.com/1116377/92476453-5c694980-f1b5-11ea-843f-910e8c132eff.png)
