### ISSUE TITLE
Implement test suites

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/kool#20]
After some initial effort we have now a test pipeline in place, and a few examples on testing some important code paths.

---

Our current graph is not very promising though, but we will get there!

![CodeCov](https://codecov.io/gh/kool-dev/kool/branch/master/graphs/sunburst.svg)

**Comment by fabriciojs** [comment]
Once #92 is merged we can check out https://codecov.io/gh/kool-dev/kool and grab ourselves a good old badge to display.

**Comment by danielsuguimoto** [comment]
After merging #95 and refactoring the entire application to use the new command builder added on #93, we will be able to mock most of the commands and increase testing coverage a lot.

**Comment by dbpolito** [comment]
I'm closing this one as we reached our initial goal which was 90% coverage, thanks @danielsuguimoto for your hard work on this one.
