### ISSUE TITLE
Create sample content/examples in rich format

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#200]
For kool 2.0, we need a new demo video using `kool preset` instead of `kool init`

**Comment by danielsuguimoto** [comment]
After merging #198, we also can use the new create command on the demo

**Comment by fabriciojs** [comment]
One option I find interesting is recording using https://asciinema.org/ and then publishing to our Blog https://blog.kool.dev.
 
The repo here can always have only an image linking to the blog post.

**Comment by fabriciojs** [comment]
Closing this because we already have some asciinema demos. The README has already been updated to point to https://asciinema.org/~kooldev

There is active work happening and soon there will more examples over there.
