### ISSUE TITLE
Fallback non-existing commands to kool run

### ISSUE THREAD

**Issue by dbpolito** [kool-dev/kool#207]
Yarn has a similar behavior, i keep running `kool reset` instead of `kool run reset`, would be great to just fallback non-existing  kool commands to kool run.

**Comment by fabriciojs** [comment]
Would be nice to hear others opinions on this. My input as previously shared in other similar discussion:

I find this fallback strategy risky and counter intuitive, as we have a handful of first-level commands within kool (start, stop, logs, etc) which are likely to eventually collide with some `kool.yml` defined script. That would be very messy and disappointing having to use two different interfaces for running commands. Also we might in the future add more first-level commands, which could bring unwarned breaking changes to specific users in their custom kool.yml scripts by chance.

Other than that I am just fond for strict interfaces, where we have one way to learn and follow. Seems simpler.

**Comment by danielsuguimoto** [comment]
@dbpolito @fabriciojs usually, when the tool gives me the opportunity to use shorten commands I use this feature. Like `yarn` does...I rarely use `yarn run`, for example. But I have no idea how yarn handles these cases that the script name is the same as an internal command. I believe it only runs a script if it is not a known command, otherwise, you should run the script with an explicit `run` command.

**Comment by danielsuguimoto** [comment]
but IMO, it is worth making a survey about it

**Comment by diegohcosta** [comment]
For me, the more visible what you are doing, the better.
It is simple to use for those who already "understand", but we have to see the didactic question.

**Comment by hudsonpereira** [comment]
Maybe if we had a prompt beforehand that would be nice. 

Like: `Did you mean kool run reset? [y[n]`.

**Comment by bessa3301** [comment]
@hudsonpereira yes! that is a great idea IMO

**Comment by dbpolito** [comment]
it's a option but what about CI? :)

**Comment by fabriciojs** [comment]
I like @hudsonpereira 's idea as well.

@dbpolito - what about CI?

**Comment by dbpolito** [comment]
Well if i run `kool reset` on CI it will fail as there is no TTY and will probably fail.

**Comment by fabriciojs** [comment]
The correct and proper feature is `kool run`, we are not talking about changing that, are we?

We are just talking about a "sugar" parameter handling, so it should be meant ONLY to "fix" usage errors - like you provided in the issue description.

**Comment by dbpolito** [comment]
Yep, what i mean is if you get used to use `kool reset` locally, then on CI you will have to add `run`... having this is better than nothing.

**Comment by danielsuguimoto** [comment]
@fabriciojs @dbpolito using cobra features, we cannot wait for the user input after typing an unknown command, neither customize the suggestions algorithm like we want to.

**Comment by fabriciojs** [comment]
> @fabriciojs @dbpolito using cobra features, we cannot wait for the user input after typing an unknown command, neither customize the suggestions algorithm like we want to.

That being the case, I guess I am good with closing this issue with no changes at this point.

**Comment by fabriciojs** [comment]
I will close as that is my understanding given @danielsuguimoto prognosis about the proposed implementation. Please feel free to comment/reopen if someone sees fit.
