### ISSUE TITLE
Commands output

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/kool#21]
Make sure that error output for any commands are properly returned back to original shell output.

https://blog.kowalczyk.info/article/wOYk/advanced-command-execution-in-go-with-osexec.html

**Comment by fbrissi** [comment]
Check here:
https://github.com/kool-dev/kool/blob/88a89a2893c038b2fa5e41c9b98ab995c1eb94cc/cmd/start.go#L37-L41

When the docker is not up, the output is only `2020/08/12 12:09:46.573708 exit status 1`

**Comment by fabriciojs** [comment]
This has been improved and we will consider fixed as of the latest release `1.0.15`.

Please open a new descriptive issue if necessary.
