### ISSUE TITLE
Proposal: design a plugin/module architecture

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#210]
**Describe the feature**

It would be nice to be able to add more functionality to kool without inflating the core source via plugin/module architecture.

**Backward compatibility concerns**

Would this be BC? No

**Comment by danielsuguimoto** [comment]
What I know so far: any binary or script can be wrapped by `kool` if we create a command for it and add it to the root command. The questions are more about which pattern and standards we should follow... the location of these binaries/scripts...maybe a path set by an environment variable? Or any executable under $PATH that starts with `kool_`? We need to think also about how we can load these plugins without affecting performance.

**Comment by fabriciojs** [comment]
Similar initial discussion: https://github.com/kool-dev/kool/issues/1

**Comment by fabriciojs** [comment]
@danielsuguimoto @dbpolito 

What about we start on this with the `kool deploy` command? removing it from the core, creating a new command `kool-deploy` that we then opt-in somehow (`kool plugin add deploy`?), and then we inject it at runtime to be available as `kool deploy`.
