### ISSUE TITLE
One Liner Install not working on Mac with zsh

### ISSUE THREAD

**Issue by dbpolito** [kool-dev/kool#215]
On Mac with zsh our current one liner is failing:

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/347400/101532079-c939de80-3972-11eb-9dc8-ab745ec144e4.png">

As an alternative we can use:

```bash
sudo bash -c "curl -fsSL https://raw.githubusercontent.com/kool-dev/kool/master/install.sh | bash"
```

But before we change it may be a good idea see other libraries how they are using and see a more standard way of doing it.

Also would be great adding a success message to this script:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/347400/101532193-f2f30580-3972-11eb-8d8f-fee67e41a5be.png">

**Comment by indiegenus** [comment]
For inspiration, take a look at the installer for Symfony CLI, which installed successfully on the same Macbook running Big Sur with `zsh`, using this one liner: `curl -sS https://get.symfony.com/cli/installer | bash`.

**Comment by dbpolito** [comment]
This should be fixed, take a look on the new script at https://github.com/kool-dev/kool#installation and if the problem persist please comment here or open a new issue.
