### ISSUE TITLE
kool create should call kool preset with the override flag

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#221]
**Describe the bug**

The framework/language's boilerplate might have one of the preset files (Laravel 8.0 comes with a `docker-compose.yml`, for example). In this case, the preset command will fail after creating the project. So, after creating the project, `kool preset` must be called with the `--override` flag

**Kool version and environment**

1.7.0

**To Reproduce**

Call `kool create` with laravel 8.0 preset

**Expected behavior**

Both project and kool files must be set succesfully

**Comment by dbpolito** [comment]
Maybe we can make it iterative, like per file ask, overwrite? y/n... like cp / mv without `-f`, and the option just mean y to all

**Comment by fabriciojs** [comment]
Bringing to this the notes on #222 - 

Latest Laravel 8 comes now out of the box with a docker-compose.yml for Laravel Sail, which makes the kool preset laravel prompt the user about overriding the files.

I am not sure how we can best handle this, couple of ideas:

Properly document that for Laravel you need the --override to start with (risky)

Have Laravel preset overriding docker-compose.yml by default?

Maybe the best: confirm if it is Laravel Sail, make Kool work with it seamlessly (keeping original Sail docker-compose.yml file, using its images).

**Comment by fabriciojs** [comment]
@danielsuguimoto @dbpolito I don't think `--override` as default behaviour is the best solution... I am imagining what kind work would be for us to support both flavours (kool running sail, or kool running kool-original images).

**Comment by dbpolito** [comment]
well a good start is asking to overwrite per file... than at least is clear to the user... Now having both we can move forward with having `kool.services.yml` file, and fallback to `docker-compose.yml` and make it smart on our code, to add -f to docker-compose commands if there is a `kool.services.yml` so it doesn't require the symlink when not there...

Downside with this approach is running `docker-compose` directly

**Comment by fabriciojs** [comment]
I would not go to `kool.services.yml` - when I said support both, is that we do not need to have our docker-compose.yml, we can use `kool` to manage Sail file itself.. maybe a "sub preset" for Laravel?

**Comment by dbpolito** [comment]
I suggest we do the simplest way for fixing it:

We always "override" but before we do we rename the file to `file.bak.YYYYMMDD` so if the project already has `docker-compose.yml` before we create this file we rename it to `docker-compose.yml.bak.20200101`.

That way we just works and the user can compare / revert if necessary.

**Comment by danielsuguimoto** [comment]
@dbpolito so, will we drop the override flag on preset command? You have my thumbs up for this!

**Comment by dbpolito** [comment]
@danielsuguimoto yes... we can remove it
