### ISSUE TITLE
Preset issue - Laravel 8 conflict

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/kool#222]
Latest Laravel 8 comes now out of the box with a `docker-compose.yml` for Laravel Sail, which makes the `kool preset laravel` prompt the user about overriding the files.

I am not sure how we can best handle this, couple of ideas:

- Properly document that for Laravel you need the --override to start with (risky)

- Have Laravel preset overriding docker-compose.yml by default?

- Maybe the best: confirm if it is Laravel Sail, make Kool work with it seamlessly (keeping original Sail docker-compose.yml file, using its images).

**Comment by fabriciojs** [comment]
@danielsuguimoto @dbpolito this is kind important, since `kool create laravel` at this point already brings this situation to the user.

**Comment by dbpolito** [comment]
This is a dupe from https://github.com/kool-dev/kool/issues/221
