### ISSUE TITLE
Exclude fake components from build process

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#224]
As discussed with the team, we don't need to compile the fake components, which are used only for testing, into the final binary files

**Comment by fabriciojs** [comment]
Another idea, other than build tag conditionals, we could suffix files with _test, not sure about any possible downsides.

**Comment by danielsuguimoto** [comment]
@fabriciojs build tags won't work at all, because the fake structs and interface are under the same package of the real ones, so the compiler understand that they must be available to entire package, so you cannot ignore them on building process. But we could use build tags if we put all tests and fakers in separated packages, keeping in the original packages only the code that will be built.

**Comment by danielsuguimoto** [comment]
> Another idea, other than build tag conditionals, we could suffix files with _test, not sure about any possible downsides.

I'm not sure, but I guess that unnecessary code will be executed on our tests, if golang executes any function inside `*_test.go` files as test cases...

**Comment by fabriciojs** [comment]
The functions executed should be only t ones prefixed with test.

Now about the build tags - you are saying we cannot ignore only one file
from one package? I didn’t get that but will follow up on research about it.

**Comment by fabriciojs** [comment]
This is not something pressing, nor causing any noticeable downsides. Can we close this?

**Comment by danielsuguimoto** [comment]
@fabriciojs yep, for me it's ok closing it...
