### ISSUE TITLE
Live preview: "kool live" command for live public preview of local environment

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/kool#225]
**Describe the feature**

Would be awesome to have some feature for allowing easy sharing of local environment. Nowadays remote working reality makes  this an even more appealing feature. This is closely what `vagrant share` and others used to do.

Basically we need some server service for proxying/tunnelling the live requests to our local environment (having the tunnelling client up locally). Something like https://github.com/beyondcode/expose could be used so we don't need to write from scratch such solution.

- Having SSL enabled would be an even more awesome plus here, but that may depend on #28.
- The TTL for a "live" link should be relatively small. The server-side handling of this feature might go into kool.dev closed source (the most we can make open, the better), but we do need to have some control.

**Backward compatibility concerns**

No breaking changes. Adding a new command only, ideally not changing any others while doing so.

**Use cases**

- Developer might have some new UI they want to share with QA/PO for a quick validation. (very important por front-end developers).
- Developer might have access to an API and share it with a co-worker that for some reason cannot run such service, unblocking them.

**Examples**

```console
$ kool start
    ...
$ kool live
   .... creating your live preview link ...
   You can share the link to preview your local environment: https://preview-2311.kool.live
```

**Comment by dbpolito** [comment]
@fabriciojs who is going to work on this one? assign and move to in progress when you define

**Comment by fabriciojs** [comment]
We are going to use `kool share` to start, still open about what is the best term.

**Comment by fabriciojs** [comment]
It is implemented and will be out in the next release as `kool share`
