### ISSUE TITLE
Simplify configuring process for the .env file 

### ISSUE THREAD

**Issue by bessa3301** [kool-dev/kool#227]
## Describe the feature

For starters, getting acquainted with Kool can be somewhat confusing when it comes up to .env files. **Note that this was observed using Kool and Laravel.**  The idea is to have some warning to pop up, or comments, or some form to remind the user to `cp .env.example .env`, rename the `DB_HOST` to `database` and `REDIS_HOST` to `cache`.

I'm not sure how we could approach this in order to make the user experience more friendly. 

## Use cases

Focused for people trying out Kool, making their experience better, thus increasing the acceptability ratio.

--- 

React with a 👍🏻 or 👎🏻  if you think that is a good idea 🙃

**Comment by danielsuguimoto** [comment]
I guess we can create a new command to set the environment variables directly in `.env` files, then we can use this new command to sync `.env` with `docker-compose.yml` in the `setup` script of the Laravel `kool.yml`, for example

**Comment by dbpolito** [comment]
hmm, maybe we can go a step further and asking on the wizard to run extra commands and doing extra execs... we could have this defined somehow on our preset template, like, ask for copy .env, ask for replace and run a few `sed //` commands.

**Comment by dbpolito** [comment]
This is a very important aspect as it's crucial to our UX and onboarding... making it as magical and smooth is going to be great.

**Comment by danielsuguimoto** [comment]
For sure! But I'd go step by step onto this. Not sure if `sed` works on powershell, for example, so maybe we should bring this kind of find and replace of `.env` files feature into `kool` first without environment dependencies, then we can improve preset/init afterward...well, we also have `kool-dev/bash` image that could help on it, I guess...

**Comment by dbpolito** [comment]
that's exactly why i created `kool-dev/bash`, good job remembering it... we need to also update our presets to use it for the cp part... as it doesn't work well on windows too...

not sure `bash` comes with `sed` installed by default but we definitely could...

the idea here: https://github.com/kool-dev/kool/blob/master/presets/laravel/kool.yml#L11

was to add an if to only cp if the file doens't exists or just add `-n ` flag, which doesn't overwrite

**Comment by fabriciojs** [comment]
@bessa3301 although some fancier solutions were imagined above, what we have done so far is improving the documentation on the steps we need to get off the ground with a Laravel application.

Please refer to this link: https://kool.dev/docs/getting-started/starting-new-project  (this will become essentially the preset doc for Laravel, still in the making)

Do you feel that covers the initial deficiency you felt on the docs for `.env` updates? If so, I would close this issue and just link it in another Prompt/Wizard issue for future reference.

**Comment by indiegenus** [comment]
As a possible useful reference, this sounds similar to Symfony Flex recipes, in the way it automatically updates configuration files.

**Comment by fabriciojs** [comment]
Closing in favour of preset refactoring at #312 .
