### ISSUE TITLE
Improve info command output

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#230]
**Describe the feature**

By default, `kool info` outputs only `kool` environment variables, but if you pass an argument it will filter any variable in the system, but no documentation explains this behavior. It would be better if we show all variables separated by context, for example, and improve how we filter these variables with the command. Also, improve the documentation about it.

**TODO**

Add to the `info` command output details on:

- Kool Version / Path
- Docker version
- KOOL_ environment variables
- Docker Composer version (if exists)
- Given the current command execution, what `kool.yml` files would be loaded (current and/or home directory?)
- Run version availability
- Kool Cloud status (if there is KOOL_API_TOKEN) and associated detail (user account/email or project)

**Backward compatibility concerns**

Would this be BC? No

**Comment by fabriciojs** [comment]
I like the feeling on needing to improve the `kool info` command.

I am not sure I dig the *show all variables...*  idea. I guess we should only display the variables that directly affect `kool` itself.

But expanding from here, we could also do:

- Tell if we are in an environment with kool.yml or not; display the available commands.
- Check if there is user context kool.yml, and display the available commands.
- If we are in a kool powered application's folder, tell if it is running or not; tell the services available;
- Run the version availability check (as we do on kool start).
- More?

So this is all like, diagnostic output that might be helpful to figuring out what is going on where we are.

What do you guys think? @danielsuguimoto @dbpolito

**Comment by fabriciojs** [comment]
Also we could check if we have credentials do Kool Cloud, and display the user/if there current application has deployments.

**Comment by danielsuguimoto** [comment]
IMO, we don't need to display available commands and services, we have `kool status` and `kool run --help` that display this kind of information, but instead of outputting the services/scripts, we can summarize them somehow...keeping the output shorter and more readable.

More
- kool version
- kool path

**Comment by fabriciojs** [comment]
> IMO, we don't need to display available commands and services, we have `kool status` and `kool run --help` that display this kind of information, but instead of outputting the services/scripts, we can summarize them somehow...keeping the output shorter and more readable.
> 
> More
> 
> * kool version
> * kool path

My point is that `kool info` is vague by nature... what is `info`? So I guess if it is as complete as possible, information wise, that would be beneficial.

**Comment by fabriciojs** [comment]
I updated the description with what I would like to have in the `info` command. @dbpolito @danielsuguimoto any more views on this?

**Comment by danielsuguimoto** [comment]
What about some info about containers? Don't need to have details about it...just some info like number of running containers, for example...

**Comment by fabriciojs** [comment]
Hum, I don't feel the overall container count would be useful.. what would be the usefulness of that number?

I mean, I understand you referred to all containers in the system. If instead, you meant when we are within a Kool project and we should then display some information about the project containers (Running or Not, what Services we have - pretty much like `kool status` - then I would agree this makes sense, is helpful and we should add such bit of information.

**Comment by danielsuguimoto** [comment]
@fabriciojs I was referring to the project containers, like `kool status` but with less details. I agree that overall info is not usefull.

**Comment by fabriciojs** [comment]
With this we will also improve the validation of versions available, and use this command at installation, to confirm Docker environment is ready to work with Kool.

**Comment by fabriciojs** [comment]
Partially implemented, and merged onto `master` already. Will be in the next release.

**Comment by fabriciojs** [comment]
This has been implemented within our [latest release 1.15.0](https://github.com/kool-dev/kool/releases/tag/1.15.0).
