### ISSUE TITLE
Error running reset script on laravel project

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#254]
**Describe the bug**

Docker-compose fails when running multiple commands scripts

**Kool version and environment**

1.9.0 on MacOS

**To Reproduce**

Run `kool run reset`

![image](https://user-images.githubusercontent.com/25229545/106609856-cdcedd80-6544-11eb-9211-8edcaed4332d.jpeg)

**Expected behavior**

The script must be executed, but it exits with an error on the second command of the script:

![image](https://user-images.githubusercontent.com/25229545/106609958-eb9c4280-6544-11eb-94c1-401f56094180.jpeg)

**Comment by danielsuguimoto** [comment]
If I run each command of the script separately, all of them work fine.

**Comment by danielsuguimoto** [comment]
If you are facing this issue, you can downgrade `kool` to version `1.8.0`. We will release a fix for this ASAP.

```bash
curl -fsSL https://kool.dev/install | DOWNLOAD_URL=https://github.com/kool-dev/kool/releases/download/1.8.0 bash
```

**Comment by fabriciojs** [comment]
Fixed will ship into the next patch release today.
