### ISSUE TITLE
Confusion to define whether the device is a TTY or not

### ISSUE THREAD

**Issue by Guiradi** [kool-dev/kool#262]
**Description**

When trying to dump the database to a local kool instance, an error was printed on the terminal indicating a possible misunderstanding about the device's origin. Here is the verbose command with the error:
$ docker-compose exec database mysql -uuser -ppass schema < ../backup.sql
the input device is not a TTY

**Kool version and environment**
kool -v: kool version 1.9.1
environment: OS Ubuntu 20.04
kool info:
 - KOOL_NAME=guilherme-ferreira
 - KOOL_GLOBAL_NETWORK=kool_global
 - KOOL_ASUSER=1000

**To Reproduce**

To reproduce the behavior, you can simply try to dump a database with kool exec.

**Expected behavior**

The database should be dumped and no answer from the terminal is expected.

**Comment by fabriciojs** [comment]
@Guiradi thanks for the report!

Please can you confirm that you could only experience this error when running the input redirection (`<`) from within some script under `kool.yml`? Well, that was the only way I could reproduce.

We have a fix under review, we should expect a patch release sometime tomorrow.

Cheers

**Comment by fabriciojs** [comment]
This should be fixed now as of `1.9.2` - https://github.com/kool-dev/kool/releases/tag/1.9.2

Thanks for the report @Guiradi !

Please reopen this issue if you need to.
