### ISSUE TITLE
Laravel db refresh command does not exits

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#270]
**Describe the bug**

Command `kool run artisan migrate:fresh --seed` is executed successfully, but it does no exit the container. A cancel signal (Ctrl+C) is necessary for further commands.

**Kool version and environment**

kool 1.9.2 on MacOS 11.2

**To Reproduce**

Run `kool run artisan migrate:fresh --seed` on a laravel project

**Expected behavior**

After executing successfully, command should exit

**Comment by fabriciojs** [comment]
@danielsuguimoto please can you gather some more information on what exactly happens and makes you believe the command will not exit?

I was not able to reproduce it in my local (MacOS with both kool@master and kool@1.9.2). Either way, I am getting the final message, and the command exits properly:

![image](https://user-images.githubusercontent.com/1116377/107363130-7dadc900-6ab8-11eb-86da-1fa614fada13.png)

Can please test on another project, maybe it is something else related to events/database state on that specific project?

**Comment by fabriciojs** [comment]
Another good test in order to determine whether it is a kool problem or an artisan problem is: `kool exec app bash` and then run `php artisan` from within the container, that way you know if it still hangs, it is a artisan/application problem, not kool.

**Comment by danielsuguimoto** [comment]
@fabriciojs the problem doesn't occur on other projects...
