### ISSUE TITLE
[ Dúvida ] - Configurar variáveis usadas no docker-compose.yml

### ISSUE THREAD

**Issue by zarpelon** [kool-dev/kool#278]
Olá pessoal,

Onde eu consigo configurar os valores de algumas variáveis usadas no docker-compose.yml?

Por exemplo "${MYSQL_USER:-root}"

Seria possível setar no kool.yml ?

**Comment by danielsuguimoto** [comment]
@zarpelon você consegue configurar essas variáveis no arquivo `.env` do projeto

**Comment by zarpelon** [comment]
Opa bacana! Muito obrigado pela resposta @danielsuguimoto =)
