### ISSUE TITLE
Atualizar a versão do composer

### ISSUE THREAD

**Issue by zarpelon** [kool-dev/kool#281]
Quando eu executo:

`kool run composer require my_package`

Então recebo:
_Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2_

Seria possível atualizar para usar o composer na versão 2? Se eu rodar o self-update provavelmente irá atualizar, mas quando terei que fazer isso em todos os projetos que usam o composer.

**Comment by dbpolito** [comment]
@zarpelon atualmente a imagem do php do kool vem com as 2 versões, quando vc instala o preset ele até pergunta qual versão vc quer usar...

Altera seu `kool.yml` pra usar `composer2`: https://github.com/kool-dev/kool/blob/master/templates/scripts/composer2.yml#L2 que já funciona...

Atualmente ainda estamos deixando o padrão no composer 1 pra não querer alguns projetos legados nosso mas a ideia é mudar o padrão logo...

:+1:

**Comment by zarpelon** [comment]
Entendi @dbpolito !

Grato pelo retorno.
