### ISSUE TITLE
Env being used for all multi-line scripts

### ISSUE THREAD

**Issue by dbpolito** [kool-dev/kool#284]
```yaml
  install-test:
    - echo $ENV_FROM_ENV_FILE # empty here
    - cp .env.testing .env
    - echo $ENV_FROM_ENV_FILE # still empty
```

I believe this was introduced by https://github.com/kool-dev/kool/pull/240

Not sure we want to change this behavior, but at least we need to document it.

**Comment by fabriciojs** [comment]
@dbpolito I see, the example you provided never worked, right? But I guess you wanted to actually provide an example of subsequent `kool run` or `kool exec`, which then in the past, that would trigger a full reload of environment (new process context), and therefore the newly created .env file would be parsed for subsequent kool calls. 

So to be clear - for anything that is not a `kool` command, like in the provided example, they will never work.

In case of a `kool` command (usually `exec` or `run`) being executed, you are making the case that it should reload the environment files for each call.

That is a grey area to me, where there are stances you probably want the new environment (based on .env) to be preserved, I am sure there are others we don't want it.

I don't believe this is a BUG, even though behavior was unintentionally changed, I do feel like the current one (having the first state only preserved) is kind preferred.

**Comment by danielsuguimoto** [comment]
@fabriciojs actually...there is a real case that stoped working...when users setup for the very first time

```yml
install:
  - cp .env.examle .env
  - kool start
```

I guess `kool start` fails because environment changes are not applied after creating `.env`...an this script is in our presets...

**Comment by fabriciojs** [comment]
@danielsuguimoto like I said in my long answer above, the situation happens only for `kool` commands, in this case the `start` command.

To return to the old behavior of "environment reload" we will have to worry about avoiding unintended loading changes on environment variables being kept over among executions.

**Comment by danielsuguimoto** [comment]
@dbpolito @fabriciojs so we should remove `cp .env.example .env` from the preset script for now and do the necessary changes on the documentation about it....or we can export `.env` variables after creating it on this specific script

**Comment by fabriciojs** [comment]
@danielsuguimoto we don't need to remove it, as it works as is now...

The `kool` process indeed won't be aware of the newly `.env` file, but, all commands themselves (kool start, artisan, composer, etc...) will because they have their own loading of the environment for what matters. So everything should be working.

Or do we have some other pressing issue that I am missing?

**Comment by danielsuguimoto** [comment]
@fabriciojs my concern is about database environment variables used on `docker-compose.yml` on the very first `kool start` inside the `setup` script....

That's the default at `.env` file
![image](https://user-images.githubusercontent.com/25229545/110996158-4b62e600-835a-11eb-8589-64886791c283.jpeg)

...and that's the default in our `docker-compose.yml` preset...
![image](https://user-images.githubusercontent.com/25229545/110996258-764d3a00-835a-11eb-9f3e-14b5e13a6780.jpeg)

but it's possible that I am misunderstanding something too

**Comment by dbpolito** [comment]
@danielsuguimoto this use case is currently working, as `docker-compose` will evaluate the envs in a child process..

What breaks is when you use the env on the kool.yml file, like:

```
scripts:
   example:
     - cp .env.testing .env
     - kool exec -e SOME=$SOME_ENV
```

In this case kool will do the env replacement, which wasn't evaluated... for our current usage everything is working fine, which make this not urgent.

**Comment by dbpolito** [comment]
I do think we should evaluate the reload the env per line, which will also make that idea of having `kool run -e` also possible...

Each run is an independent run, like running manually one by one

**Comment by fabriciojs** [comment]
I am closing this in favour of https://github.com/kool-dev/kool/issues/290 - so we handle both situations at once.
