### ISSUE TITLE
Wizard Interativo não aparece

### ISSUE THREAD

**Issue by zarpelon** [kool-dev/kool#286]
Olá, estava seguindo as orientações para startar um novo projeto e usei comando: 

 `kool create laravel my-project`

Porém logo após não apareceu o wizard interativo

Fonte: https://kool.dev/docs/getting-started/starting-new-project

**Comment by dbpolito** [comment]
Qual versão do `kool` vc está? `kool --version`

Provavelmente se rodar `kool self-update` deve resolver esse problema :+1:

**Comment by fabriciojs** [comment]
@zarpelon obrigado pelo report.

Se possível, você teria o outout do `kool create` no terminal? Aparentemente ocorreu algum erro inesperado antes do wizard.

Num rápido teste, com a última versão, tive sucesso em chegar no wizard.

![image](https://user-images.githubusercontent.com/1116377/110642144-80700c80-8191-11eb-9d2d-c3020e316679.png)

Se possível também reportar o Sistema Operacional, qual Shell (bash, zsh) está usando.

**Comment by zarpelon** [comment]
Estava na 1.7.0, acabei de atualizar. Vou executar novamente, momento.

![image](https://user-images.githubusercontent.com/264762/110643264-ac3fc200-8192-11eb-93ec-824200af5443.png)

**Comment by dbpolito** [comment]
@zarpelon nós tb temos um slack https://join.slack.com/t/kool-dev/shared_invite/zt-jeh36s5g-kVFHUsyLjFENUUH4ucrxPg caso queira entrar lá, é até mais fácil pra conseguir suporte pra esse tipo de problema...

**Comment by zarpelon** [comment]
@dbpolito não consigo entrar... somente e-mails com o domínio específico.

![image](https://user-images.githubusercontent.com/264762/110644331-bf06c680-8193-11eb-8d94-cdadf6447b29.png)

**Comment by dbpolito** [comment]
opa, tenta d novo... liberei aqui

**Comment by zarpelon** [comment]
![image](https://user-images.githubusercontent.com/264762/110645411-b4006600-8194-11eb-8b50-6da31b6f3a6d.png)

Depois eu removo esse issue, hehe.

**Comment by dbpolito** [comment]
Nossa, slack todo bugado heim, gerou outro link:

https://join.slack.com/t/kool-dev/shared_invite/zt-ntmkyjog-DHOiddbBnhY796KaABUhzg

**Comment by fabriciojs** [comment]
@zarpelon depois do Upgrade de versão do kool, o Wizard funcionou corretamente? Podemos fechar esta issue?
