### ISSUE TITLE
Helper for API mocking - mock HTTP API in your local environment

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/kool#29]
Would be to help developers adopt easy mocking solutions, either adopting or generating one.

One could simple spec up handful of endpoints with exact signatures (methods + parameters) and then serving that from a container, which would make some integrations/local development workflow a lot better.

**Comment by danielsuguimoto** [comment]
@fabriciojs would be too tricky building by ourselves an image that could serve an API given a configuration file? https://medium.com/@rafaelacioly/construindo-uma-api-restful-com-go-d6007e4faff6

**Comment by fabriciojs** [comment]
This a whole microservice idea instead of an actual `kool` feature. Mirage in JS and others mocking APIs are on the rise, it may make sense for us to simply document/suggest some of them with nice and simple preset/snippets.
