### ISSUE TITLE
Forwarding arguments on exec/run/docker escaped by --

### ISSUE THREAD

**Issue by dbpolito** [kool-dev/kool#293]
This works but has very bad UX and no documentation at all... we might need to think a better way for handling this, really mapping options or improve docs.

**Comment by fabriciojs** [comment]
@dbpolito I feel good simply adding an entry to each command's doc page where it is most valuable for usage (the `--`, the commands you mentioned) telling about the `options end`. I would add it to the Long Description of the command.

On this topic we know how `kubectl` handles this - they deprecated not using, so they will enforce having `--` for commands/arguments proxying in future versions. I am not a fan of that, I don't think our share of usage pays off going any road other than some documentation entry.
