### ISSUE TITLE
How to migrate from FWD to start using Kool

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/kool#31]
Migrating from FWD

- First of all, make sure FWD is not running.

```
fwd stop
```

- Have kool installed; check for latest version

```
kool -v
```

- Call init, and override files.

```
kool init <preset> --override
```

- Check all file changes and adapt as necessary
    - kool.yml Node version/NPM/Yarn usage; 
    - docker-compose.yml: update your base images properly as needed (https://hub.docker.com/repository/docker/kooldev/php/tags)

**Comment by danielsuguimoto** [comment]
* run it after stopping containers with `fwd stop`
```
docker network prune
```

**Comment by fabriciojs** [comment]
Once we have a de facto guide here we should then PR an Abandoned notice onto fwd so we redirect people from there to Kool.

**Comment by fabriciojs** [comment]
Since `fwd` adoption was very restricted to Firework team and projects this is not a must to have.

Closing considering the documented steps above still worth for whoever needs to migrate.
