### ISSUE TITLE
Erro ao executar o comando kool logs

### ISSUE THREAD

**Issue by zarpelon** [kool-dev/kool#318]
Estou tentando executar o comando kool logs e apresenta o seguinte erro:

![image](https://user-images.githubusercontent.com/264762/117155632-530b9d80-ad93-11eb-8bad-73cbe0aace0e.png)

Pelo que pudemos averiguar se trata da versão do docker-compose estar desatualizada! A versão é: 1.23.1

Outro ponto é que um dos containers estava down.

Depois de atualizado o docker-compose para versão 1.27 o erro não aconteceu mais.

**Comment by fabriciojs** [comment]
Obrigado @zarpelon por abrir esta issue!

@dbpolito @danielsuguimoto - the problem described above is solely related to the Docker Compose version available. We need to introduce a validation flow to tell whether we should or not use the available Docker Compose version. This also touches #309 ground as well, we need to think of them as a whole.

Any suggestions on how to tackle this are welcome.

**Comment by danielsuguimoto** [comment]
`docker compose` is still an experimental feature, we should keep an eye on it, but no actions are need right now. About `docker-compose` version, we already have a fallback in case of it is not installed, so we can use this same fallback for old version, IMO.

**Comment by fabriciojs** [comment]
This is related to version assertion and the decision-making on whether to use or not local available commands instead of running them through a new container.

As a *band-aid* for now and future newcomers/testers, I would propose we add such validation on the install script, for now, so we know that when people install, we are in the "right" place.

**Comment by fabriciojs** [comment]
Since this is just a Docker Compose version issue, we will be handling at https://github.com/kool-dev/kool/issues/230 - alerting users in advance about old versions.
