### ISSUE TITLE
Wrong version when using the version flag

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#32]
It seems that version `1.0.11` is hardcoded in `cmd/root.go`, so it is showing the wrong version.

https://github.com/kool-dev/kool/blob/089a67f6fb6951cd47d8da60350ed3671c8cba2f/cmd/root.go#L13

**Comment by fabriciojs** [comment]
Yeah the version should become a variable that we pass in to `build_artifacts` script, or something like that, that we must then provide each time we generate the binaries.

**Comment by fabriciojs** [comment]
Got an improvement to `master`. Now we must provide a environment variable KOOL_VERSION to `build_artifacts.sh` script which is then going to be used for replacing `cmd.version` variable with `-ldflags` during compile time.
