### ISSUE TITLE
Mensagem está errada ao rodar kool start --remove-orphans

### ISSUE THREAD

**Issue by zarpelon** [kool-dev/kool#326]
Eu removi um container do docker-compose e ao rodar o kool start eu recebo essa mensagem:

![image](https://user-images.githubusercontent.com/264762/118002547-1b19d280-b31e-11eb-8047-609ab03486d0.png)

O problema que fica a impressão que o usuário deveria rodar o comando: `kool start --remove-orphans`

E ao fazer isso eu recebo:

![image](https://user-images.githubusercontent.com/264762/118002639-31c02980-b31e-11eb-83db-65404fd4badf.png)

**Comment by fabriciojs** [comment]
This will be handled at https://github.com/kool-dev/kool/issues/279 along with other error output situations that require improvements. Closing this now, and progress should be discussed/followed in the centralized issue.
