### ISSUE TITLE
Rebuild on start/restart

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#349]
**Describe the feature**

Add a flag to rebuild services before starting or restarting them

**Backward compatibility concerns**

Would this be BC? No

**Use cases**

`kool start --rebuild` and `kool restart --rebuild`

**Comment by fabriciojs** [comment]
@danielsuguimoto do you mean adding the `--build` flag to `docker-compose up`? Or really calling `docker-compose build`?

**Comment by danielsuguimoto** [comment]
> @danielsuguimoto do you mean adding the `--build` flag to `docker-compose up`? Or really calling `docker-compose build`?

@fabriciojs calling `docker-compose build`...just in case of Dockerfile changes and images updates...

**Comment by fabriciojs** [comment]
The issue of base images having updates, is a real UX concern. Right now you need to do `docker pull <image>` yourself. We may come up with some helper for that.

**Comment by danielsuguimoto** [comment]
`docker-compose build` has a `--pull` flag...but yeah...for images outside of `docker-compose.yml`, `docker pull` will be still necessary...

**Comment by fabriciojs** [comment]
OK we may add `docker-compose build --pull` that should suffice. 

https://docs.docker.com/compose/reference/build/

**Comment by fabriciojs** [comment]
yeah, we will figure something out, parsing what is not built, there is a `docker-compose pull` I believe.

**Comment by fabriciojs** [comment]
This has been implemented and is available for review. Will go in the next release.

**Comment by fabriciojs** [comment]
This has been released!
