### ISSUE TITLE
Just an idea: kool.yml on user level

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#35]
Hey, guys! How about looking for kool scripts inside a user's home directory/subdirectory? Is it possible?

**Comment by fabriciojs** [comment]
Awesine idea! so we can have global scripts available. Questions that arise:

- Should we make `kool run` look for scripts on both local and user environment folders? What should we do if a same script exists in both? have precedence or explode an error?

- Other questions?

**Comment by danielsuguimoto** [comment]
I guess we should prioritize the project script. But it would be nice to warn the user that the project script was executed instead of his.

**Comment by fabriciojs** [comment]
This has been implemented and merged onto master! Will be in the next release.
