### ISSUE TITLE
Kool for aarch64 

### ISSUE THREAD

**Issue by hataiit9x** [kool-dev/kool#353]
**Describe the feature**

A clear and concise description of what the feature idea is. Please make sure you didn't find an existing issue with the same subject.

**Backward compatibility concerns**

Would this be BC?

**Use cases**

Situations and audience for this feature.

**Examples**

If applicable, add pseudo-commands examples to help explain your idea.

**Comment by fabriciojs** [comment]
Hello @hataiit9x !

I am not familiar with `aarch64` - quickly researching it's the ARMv8, right? We currently have `kool-linux-arm7`, we will look into this.

Out of curiosity - what hardware currently would benefit from such arch distribution?

**Comment by fabriciojs** [comment]
PR ready - https://github.com/kool-dev/kool/pull/382 - this should go into upcoming release.

**Comment by fabriciojs** [comment]
This has been fixed within our [latest release 1.15.0](https://github.com/kool-dev/kool/releases/tag/1.15.0).
