### ISSUE TITLE
PHP Web Sockets Extension Support

### ISSUE THREAD

**Issue by hasnatwe** [kool-dev/kool#356]

**Comment by fabriciojs** [comment]
Hello @hasnatwe ! Thanks for creating this request!

Please, can you elaborate a bit further on what the enhancement would be exactly? Do you mean having [Sockets](https://www.php.net/manual/en/book.sockets.php) enabled in our PHP images? I can move with this issue once we have more details to https://github.com/kool-dev/docker-php to handle that.

In case what you mean is just "how" to do it, we certainly can help with documentation.

**Comment by dbpolito** [comment]
If what you mean is the `PHP Extension` at our `PHP Image` it was fixed by https://github.com/kool-dev/docker-php/pull/33.

To see this update just run `kool start --rebuild` which should pull latest image version.

**Comment by hasnatwe** [comment]
@fabriciojs @dbpolito Thanks a lot to you all for quick response. I think the issue is solved in kool php branch now. Thanks
