### ISSUE TITLE
Feature: CodeIgniter Preset

### ISSUE THREAD

**Issue by ajmeireles** [kool-dev/kool#369]
Hi!

I would like to suggest introducing presets for creating projects based on CodeIgniter 4, a widely used PHP framework that can add a lot of Kool usage by other developers.

To help with this, I created the PR which can be seen at this link:
https://github.com/kool-dev/kool/pull/370

**Comment by dbpolito** [comment]
This has been tagged: https://github.com/kool-dev/kool/releases/tag/1.14.0

Thank you for the contribution 🚀
