### ISSUE TITLE
Proposal: kool wait

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/kool#41]
Waiting for a valid state is a recurring requirements for a lot of tasks, namely containers start synchronisation for example.

Some other tools implement a nice approach which I believe might make sense to bring to kool as well.

`kool wait http://other-container:8000`  - would wait until getting a valid 200 out of that URL.

`kool wait tcp://mysql:3306` - waits until Mysql is accepting connections.

`kool wait file:///path/to/some/file` - waits until that file exists.

---

Other than the basics (http(s)/tcp) would be great to have some extra helpers for example:

`kool wait  elastic://elastic-container:9200` - which would not only wait for HTTP server to be up, but for a health state as well.

`kool wait mysql://mysql:3306` - not only awaits for Mysql accepting connections but also being live for querying.

---

Yet another level of extras could be generic content checking / status / etc.

`kool wait --http-status=302 http://other-container:8000` - waits for a redirect response.

`kool wait --timeout=25s --check-interval=2s tcp://ip:1020`- changes the timeout for waiting (default to 1 minute?); changes the interval between checks 

`kool wait --text="Kool" file://path/to/file` - waits until the target file contains the content provided "Kool"

**Comment by dbpolito** [comment]
For Reference: We already do something like that using https://github.com/jwilder/dockerize wait feature with:

```
wait-services: kool exec app dockerize -wait tcp://database:3306 -wait tcp://cache:6379 -timeout 30s
```

**Comment by fabriciojs** [comment]
A testing tool, that in parts steps on this same feature - used for healthchecks - https://github.com/aelsabbahy/goss 

Specially for docker-compose - https://github.com/aelsabbahy/goss/tree/master/extras/dcgoss

We should understand it.

**Comment by fabriciojs** [comment]
As pointed by Daniel we already use `dockerize` and there does seem to be much reason or room for improvement to a new implementation of the same tool at the moment. If needed by we can revisit this topic in the future upon a new perspective.
