### ISSUE TITLE
self-update requires `sudo` on Mac

### ISSUE THREAD

**Issue by dbpolito** [kool-dev/kool#410]
![image](https://user-images.githubusercontent.com/347400/161603068-ff340a7d-7059-484e-a9c9-9cfd3e500cec.png)

With sudo everything worked fine, maybe we need to improve error message or ask for sudo if needed like we do on install

**Comment by fabriciojs** [comment]
@dbpolito I can't reproduce; is this something you can reproduce always?

**Comment by fabriciojs** [comment]
PR created with a slight improvement regarding this; will be in the next release.
