### ISSUE TITLE
Proposal: Windows support

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/kool#42]
Right now the best way to use Kool on Windows is actually through WSL2 - which is pretty much a Linux environment so things should work mostly out-of-the-box.

Now running under Windows is a big question mark due to environment differences - executing docker, docker-compose, flags parsing, etc.

We have people testing that in an experimental fashion at this moment.

**Comment by fbrissi** [comment]
I stiil testing this, but it seems to be very promising for now.

![image](https://user-images.githubusercontent.com/339706/92105232-eb8eef80-edb8-11ea-8cc7-4bd872b92b57.png)
![image](https://user-images.githubusercontent.com/339706/92105259-f6e21b00-edb8-11ea-9859-b1f7bd191aeb.png)
![image](https://user-images.githubusercontent.com/339706/92105375-23963280-edb9-11ea-8639-4886664e962c.png)
![image](https://user-images.githubusercontent.com/339706/92105330-0feacc00-edb9-11ea-94ae-4781a3d82d25.png)

**Comment by fabriciojs** [comment]
This has been added on latest release 1.0.16.

But we have an issue - Windows tells the installer is a security risk. In order to solve that we need to sign the program.

@fbrissi pointer that out: https://docs.microsoft.com/pt-br/windows/msix/package/sign-app-package-using-signtool

**Comment by fabriciojs** [comment]
Windows store - can we delivery through there?

**Comment by wesleyhf** [comment]
I think windows store is a good way to go, it will keep everything simple, just go to store and click install!

https://docs.microsoft.com/en-us/windows/uwp/publish/

**Comment by fabriciojs** [comment]
@cesramires - your notes about WSL are great - maybe you could provide a PR to add this somewhere in the docs/  markdown files? Installation section, maybe a new page linked, with WSL specifics.

**Comment by fabriciojs** [comment]
About Windows store, I am moving this to be analysed at https://github.com/kool-dev/kool/issues/89.
