### ISSUE TITLE
Move from `docker-compose` to `docker compose`

### ISSUE THREAD

**Issue by dbpolito** [kool-dev/kool#435]
It should be feature complete by now.

**Comment by danielsuguimoto** [comment]
links:
- https://github.com/docker/compose-switch
- https://pkg.go.dev/github.com/docker/libcompose

**Comment by fabriciojs** [comment]
The PR is ready for review and this will be in the next release.

**Comment by fabriciojs** [comment]
The implementation that requires Compose V2 has been released today with version 1.19.0.

One problem emerged - it seems that Linux installations from the CLI lack the Compose V2 plugin, so you might need to install it manually.

https://docs.docker.com/compose/install/#scenario-two-install-the-compose-plugin

Docs on how to install the plugin: https://docs.docker.com/compose/install/linux/#install-using-the-repository
