### ISSUE TITLE
Comando kool logs não exibe mensagem de dependência

### ISSUE THREAD

**Issue by zarpelon** [kool-dev/kool#455]
diogo@dev:~$ kool --version
kool version 1.20.0

Pessoal, percebi que depois da atualização para essa versão, uma versão mais recente do docker compose é requerida. O que acontece é que ao rodar o comando "kool logs" ele simplesmente joga o output como se fosse o comando do "kool help"

Eu só consegui identificar o problema das dependências quando rodei o "kool start". 

Acredito que seria interessante ter essa validação no comando do kool logs entre outros, para indicar o caminho ao usuário.

**Comment by fabriciojs** [comment]
We have this validation during installation. Keeping Docker updated to latest version and enabling Docker Compose v2 should be the norm, so we are not seeing more of this problem in the installed user base.

We will keep monitoring and adding safe guards when needed, but at this time doesn't seem like adding the check to all commands (i.e logs) makes sense given the cost to running it before hand.
