### ISSUE TITLE
Ajustar o cli quando executa kool preset

### ISSUE THREAD

**Issue by zarpelon** [kool-dev/kool#466]
Ao rodar o kool preset, quando selecionado PHP e Laravel, está com as opções duplicadas, acredito que deveria ter a versão do PHP 8.1 e então depois a 8.2

![image](https://github.com/kool-dev/kool/assets/264762/f289e122-8bbb-4156-a2bb-0357a52c7bbc)

**Comment by fabriciojs** [comment]
This was fixed with the last release.
