### ISSUE TITLE
adonis: not found (exit status 1) when using podman

### ISSUE THREAD

**Issue by yasirmturk** [kool-dev/kool#472]
**Describe the bug**

I created adonis app using the instructions here;
https://kool.dev/docs/presets/adonisjs

**Kool version and environment**

kool version 2.1.1

**To Reproduce**

1. create application
2. edit .env
3.  kool run setup

`not found (exit status 1)`

**Expected behavior**

Once kool run setup finishes, you should be able to access your new site at http://localhost:3333/ and see the AdonisJs "It works!" welcome page. Hooray!

**Screenshots**

![Screenshot 2023-09-12 at 16 47 15](https://github.com/kool-dev/kool/assets/306691/d2764550-4dc6-43ef-b3a8-e241e6b5b2ee)

**Additional context**

I am using podman with docker and compose support
![Screenshot 2023-09-12 at 16 54 10](https://github.com/kool-dev/kool/assets/306691/fe79d93b-126f-4c2d-9b27-a8653def7939)

**Comment by fabriciojs** [comment]
@yasirmturk sorry for the delay on this.

I have made a few tweaks to the Adonis preset and confirmed it is working now; should merge and release a minor version within the upcoming week.

Will make more tests on your specific Podman setup, but it should not be a problem.

**Comment by fabriciojs** [comment]
Latest release got fixes for the Adonis preset, this should be fixed now.
