### ISSUE TITLE
Não consigo instalar no Windows 11

### ISSUE THREAD

**Issue by Henriquex25** [kool-dev/kool#473]
Conforme a documentação, baixei o .exe do repositório https://github.com/kool-dev/kool/releases

Quando clico no executável para iniciar a instalação, aparece o seguinte erro

![image](https://github.com/kool-dev/kool/assets/88984677/44067ece-8792-4963-bca0-f5506dae6ed6)

Já tentei excluir e baixar o arquivo novamente, já tentei executar como administrador, porém sem sucesso

**Comment by MannyDorelli** [comment]
Not working for me as well, even with Windows 10.
Seems only working using 2.0.0 installer, next versions are corrupted.

**Comment by fabriciojs** [comment]
Hey @MannyDorelli and @Henriquex25 - sorry for the delay on this report.

Unfortunately we haven't been able to keep up with support for Windows natively - I don't think we currently have community using it - as anytime a problem surfaced around it we always suggested the **WSL2 solution** - and that is the same I would suggest you guys. With WSL2 folks get about the same Linux, which is how the tool was initially intended to work.

Is there a strong argument in your end on why you want or need to use containers on Windows?

**Comment by fabriciojs** [comment]
`master` branch already got the documentation updates, and upcoming soon major release v3 is going to drop the native Windows build.

You can still use Docker for Desktop on Windows, but you have to install `kool` and run it from a WSL2 terminal - which will communicate with your Docker for Desktop seamlessly.
