### ISSUE TITLE
docker start --no-daemon

### ISSUE THREAD

**Issue by dbpolito** [kool-dev/kool#61]
Helpful for node apps...

**Comment by fabriciojs** [comment]
@dbpolito do you think this is indeed important   / still relevant?

**Comment by fabriciojs** [comment]
Let's have the `--fg` comamnd

**Comment by dbpolito** [comment]
`--fg` is too obscure, isn't?

**Comment by fabriciojs** [comment]
stands for `foreground`, same used on some other systems... I guess is best to avoid negation, going to an affirmative option instead.

**Comment by fabriciojs** [comment]
what else could we use?

**Comment by dbpolito** [comment]
well, `--foreground` then...

**Comment by fabriciojs** [comment]
This has been implemented and is targeted to next release.
