### ISSUE TITLE
Run kool on vscode tasks

### ISSUE THREAD

**Issue by brurubio** [kool-dev/kool#71]
MacOS: Catalina (version 10.15.6)
Terminal: Version 2.10 (433)
Vscode: Version: 1.48.2

Trying to use kool commands on VSCode tasks, but it gives the following error:

```
> Executing task: kool start <

2020/09/08 11:02:10.763438 exec: "docker": executable file not found in $PATH
The terminal process "/bin/bash '-c', 'kool start'" failed to launch (exit code: 1).
```

I've checked the docker path, and docker exists on `$path`: `/usr/local/bin/docker`

The command works well when running on mac terminal or vscode terminal.

Follows my tasks.json file:

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "kool: start",
      "type": "shell",
      "command": "kool start",
      "runOptions": {
        "runOn": "folderOpen"
      },
      "presentation": {
        "clear": true,
        "showReuseMessage": false,
        "reveal": "always",
        "panel": "new",
      }
    },
    {
      "label": "yarn: watch",
      "dependsOn": [
        "kool: start"
      ],
      "type": "shell",
      "command": "kool run yarn watch",
      "runOptions": {
        "runOn": "folderOpen"
      },
      "presentation": {
        "clear": true,
        "showReuseMessage": false,
        "reveal": "always",
        "panel": "new",
      }
    },
  ]
}
```

**Comment by danielsuguimoto** [comment]
https://stackoverflow.com/questions/56552022/vscode-how-to-run-docker-in-a-task-docker-build-task-does-not-work

**Comment by fabriciojs** [comment]
@brurubio did the solution on StackOverflow referenced above by Jun fixed it for you?

**Comment by fabriciojs** [comment]
This should be working properly now as we improved our TTY detection.
