### ISSUE TITLE
kool stop: Stop containers individually

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#87]
Add the possibility of stoping containers individually. 

Ex.: `kool stop chromedriver` or `kool stop --services=chromedriver`

**Comment by fabriciojs** [comment]
👍🏻  for the first suggestion, having the services as an argument list.

**Comment by danielsuguimoto** [comment]
@fabriciojs then, should we change the `start` command as well? Today, it expects the `services` flag to specify which services it should start. So we can have both commands following the same pattern.

**Comment by fabriciojs** [comment]
@danielsuguimoto I like and agree, we should change them both to be parameters list.

**Comment by danielsuguimoto** [comment]
Start command changes made on #104

**Comment by fabriciojs** [comment]
`docker-compose down` which is our default behaviour to map `kool stop` to, does not allow us to pick which containers to stop/remove.

![image](https://user-images.githubusercontent.com/1116377/95019325-13cd7080-063b-11eb-87d7-09e4b99a53a7.png)

Maybe we could fork the flow - if we specify services, we just `docker-compose stop` (which then must be incompatible with `--purge`), if no services are specified - we then default back to `docker-compose down`.

**Comment by danielsuguimoto** [comment]
We can also use `docker-compose rm` command. It stops and removes the containers, but we won't be able to remove the related volumes, since it removes only the unnamed ones.

![image](https://user-images.githubusercontent.com/25229545/95084735-a9790680-06f4-11eb-829f-eb801f31e723.png)
