### ISSUE TITLE
Self Update On Windows

### ISSUE THREAD

**Issue by fbrissi** [kool-dev/kool#88]
Self Update need administration to execute.
I think the simplest way to solve this, change installation locations.
Currently is in Program Files, I think that the Application Directory don't need permission.

![image](https://user-images.githubusercontent.com/339706/92920028-f294ae00-f407-11ea-817b-69f538b431fd.png)

https://github.com/kool-dev/kool/blob/cbe7ba9c97edac4b40d1d2bb95a7665580c32194/inno-setup/kool.iss#L19

My suggestion, change all {autopf} to {app}
See: https://jrsoftware.org/ishelp/ in [Dirs] section

**Comment by fabriciojs** [comment]
I think it is OK to have the need of Admin privilegies to update... that is expected for most users I guess.

What I suggest we do is improve error handling within `self-update` and given the running OS we display a proper help message / instructions on how to upgrade (in case of Windows, asking to open prompt as administrators to perform this action).

**Comment by fabriciojs** [comment]
This will be needed to Linux as well (`sudo` to write at destiny path). Also we should also note error in the same situation as #15  mentions about another kool process running (on Linux is an issue at least).

**Comment by fabriciojs** [comment]
What do you think @dbpolito @danielsuguimoto ?

**Comment by dbpolito** [comment]
I agree, improving the error handling and adding good documentation about it should work around this problem.

**Comment by danielsuguimoto** [comment]
I agree as well. Windows users expect to be prompt about permissions. Messages and documentation to guide them are enough.

**Comment by fabriciojs** [comment]
To sum up what is left here:

- Improve error handling on `self-update` to alert user based on their OS, what step to take to fix it.
