### ISSUE TITLE
Proposal: Placeholders on kool.yml

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#96]
Use placeholders on kool.yml for arguments, like a bash script? E.g.: `$1`, `$2` and so on...

This way we can use arguments in multi-lines kool scripts

Example:
```yml
script:
  - command1 $1
  - command2 $2 $3
```

Then we can call: `kool run script arg1 arg2 arg3`

**Comment by danielsuguimoto** [comment]
@fabriciojs @dbpolito what if we use flags for this?

Command: `kool run script --name John --age 23
Script:
```yml
script:
  - echo ${name}
  - echo ${age}
```

**Comment by dbpolito** [comment]
I like the idea, would be even better if the var is not provided, kool would ask it... so it would check first before running...

Maybe would be better creating some prefix? like `${KOOL_VAR_NAME}` and then `kool run --var="name=John"`, not sure...

**Comment by dbpolito** [comment]
terraform has a way for these kind of variables, and it allows you providing a env var `TF_VAR_SOMETHING` or `--var`, take a look there for inspiration.

**Comment by fabriciojs** [comment]
This an interesting feature that have been talked about in the early days of creating multi-lines commands and restricting extra parameters for them. Given that I would like to know if we have any real use cases that served as a push to move towards this, prioritising it?

About the UX there are several options that we can easily think imagine. We need to really plan and test what gives us the best UX keeping our goals of easiness, and overall UX feel. (maybe there were further talks about this that didn't make to this ticket for record tracking?)

**Comment by danielsuguimoto** [comment]
at project level I don't have any specific case in mind now, but I use some workarounds my personal `kool.yml`

https://github.com/danielsuguimoto/kool-scripts/blob/master/kool.yml

**Comment by fabriciojs** [comment]
Closing this as in, removing from any short term roadmap.
