### ISSUE TITLE
Browse container files or exec a bash command

### ISSUE THREAD

**Issue by danielsuguimoto** [kool-dev/kool#98]

**Comment by fabriciojs** [comment]
Running a "bash" within a container depends on the container image - if it has sh, or bash, or any other shell program we can use. As for listing, the dependency I guess is the `ls` command existing in the container.

What you imagine being the use case for this? I guess that documentation should suffice - as in, if you wanna open a shell within a container, all you have to do is `kool exec <service> <shell>`, i.e `kool exec app bash` for any kool environment with the default Laravel preset.

**Comment by danielsuguimoto** [comment]
@fabriciojs the idea was opening a shell within a container. But you're right, it looks better as a kool script than a kool command.

**Comment by fabriciojs** [comment]
👍🏻  let's add that to our preset and to the documentation.

**Comment by dbpolito** [comment]
Just a reminder that we have a new very simple image: https://github.com/kool-dev/docker-bash

That i created to make some compatibility improvement to our presets, so you can run something like `kool docker kooldev/bash bash`

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/347400/93367956-9d033b80-f823-11ea-8401-4c8b581b288f.png">

So yeah, we have the option to exec on one of our containers or a separate docker run

**Comment by fabriciojs** [comment]
So based on the initial discussion here, I would say we need to at least address the `ssh-ing` in a container in our docs to suffice the original need @danielsuguimoto had in mind with a possible extra feature.

**Comment by fabriciojs** [comment]
This documentation update is part of work @indiegenus is working on.
